# Generated by 1Password migration. Source: op://Dev/VibeCaddie .env.local
# Use:  op run --env-file=.env.local.tpl -- <command>

SITE_PASSCODE=op://Dev/VibeCaddie .env.local/SITE_PASSCODE
DATABASE_URL=op://Dev/VibeCaddie .env.local/DATABASE_URL
OPENROUTER_API_KEY=op://Dev/VibeCaddie .env.local/OPENROUTER_API_KEY
OPENROUTER_MODEL=op://Dev/VibeCaddie .env.local/OPENROUTER_MODEL
GOOGLE_SEARCH_API_KEY=op://Dev/VibeCaddie .env.local/GOOGLE_SEARCH_API_KEY
GOOGLE_SEARCH_ENGINE_ID=op://Dev/VibeCaddie .env.local/GOOGLE_SEARCH_ENGINE_ID
GOLF_COURSE_API_KEY=op://Dev/VibeCaddie .env.local/GOLF_COURSE_API_KEY
